# Add once to ~/.config/hypr/autostart.conf.
exec-once = librepods --hide

# Optional bindings for ~/.config/hypr/bindings.conf.
bind = SUPER SHIFT, A, exec, librepods
bind = SUPER CTRL, A, exec, librepods-ctl noise:anc
bind = SUPER CTRL, T, exec, librepods-ctl noise:transparency
